// @generated by scripts/gen-ffi-abi-contract.py from
// crates/veilclient-ffi/include/veil_ffi.h -- DO NOT EDIT BY HAND.
//
// Regenerate with ./scripts/regen-ffi-header.sh; CI runs the same script
// and diffs the result, so an edit here is reverted by the next run.
//
// The hash of the generated C header, compiled into the library and handed to
// foreign callers by `veil_abi_contract_hash()`. A caller that carries a
// different one was built against a different ABI: same symbol names, possibly
// different signatures, and calling through it is memory corruption rather
// than a missing-symbol error.

/// SHA-256 of `include/veil_ffi.h`, lowercase hex, NUL-terminated.
///
/// Excluded from cbindgen's output (see `cbindgen.toml`) -- a header that
/// contained its own hash could never be regenerated to a fixed point.
pub const VEIL_ABI_CONTRACT_HASH: &core::ffi::CStr =
    c"df8334a5e6ef21c993561b98e4f2e1133d5c195effdbbf165ab8007e1a90f31d";
