//! Minimal UDP mapping discovery + simultaneous hole punch for Stage B P2P.
//!
//! The reflector is intentionally not STUN-compatible. Every request and
//! response is exactly 64 bytes, so an exposed reflector cannot amplify
//! traffic. A 128-bit attempt token is generated by the caller and exchanged
//! through Veil's existing E2E signaling; matching it authenticates punch
//! packets well enough to reject off-path injection before QUIC takes over.

use std::{
    collections::HashSet,
    future::Future,
    io,
    net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr},
    time::Duration,
};

use tokio::{net::UdpSocket, time};

const MAGIC: &[u8; 8] = b"VEILUDP1";
const KIND_DISCOVER: u8 = 1;
const KIND_DISCOVER_REPLY: u8 = 2;
const KIND_PUNCH: u8 = 3;

/// Domain separators for the network binding below.
const NETWORK_TAG_CONTEXT: &str = "veil/nat/udp-punch/network-tag/v1";
const TOKEN_BINDING_CONTEXT: &str = "veil/nat/udp-punch/token-binding/v1";

/// Tag shared by every node that configures no obfs4 PSK, so the open veil
/// keeps punching among itself exactly as it did before this binding existed.
const PUBLIC_NETWORK_TAG: [u8; 32] = *b"veil.public.udp-punch.network.v1";

/// Which veil a punch belongs to.
///
/// A punch used to be authenticated by the attempt token alone, and the token
/// travels over signalling — so it crosses any boundary that signalling
/// crosses. Two nodes on *different* veils could therefore complete a punch
/// and promote it into a full session, which is how a testnet client ended up
/// holding a session with a production seed: the only thing separating the two
/// deployments was the obfs4 PSK, and a punched QUIC path never touches obfs4.
///
/// The PSK is the value a deployment already ships to exactly its own members,
/// so it is what the punch is bound to. Nodes with no PSK share
/// [`PUBLIC_NETWORK_TAG`] and are unaffected.
///
/// ⚠️ This is a correctness boundary, not a security one: the PSK ships inside
/// every release binary, so it stops accidents, not a deliberate joiner. Real
/// isolation is `network_gate` (P-Net membership certs) in the handshake.
pub fn network_tag(obfs4_psk: Option<&[u8; 32]>) -> [u8; 32] {
    match obfs4_psk {
        Some(psk) => blake3::derive_key(NETWORK_TAG_CONTEXT, psk),
        None => PUBLIC_NETWORK_TAG,
    }
}

/// The token actually put on the wire: the signalled token bound to our veil.
///
/// Derived rather than sent, so the packet layout is unchanged (still 16 bytes
/// at `[10..26]`) and so an observer of signalling — which carries the *bare*
/// token — still cannot produce a valid punch packet without also knowing the
/// network tag.
fn bound_token(token: [u8; 16], network_tag: &[u8; 32]) -> [u8; 16] {
    let mut hasher = blake3::Hasher::new_derive_key(TOKEN_BINDING_CONTEXT);
    hasher.update(network_tag);
    hasher.update(&token);
    let mut out = [0u8; 16];
    out.copy_from_slice(&hasher.finalize().as_bytes()[..16]);
    out
}

/// What a punch attempt observed.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct PunchOutcome {
    /// Peer-reflexive address to promote, when the punch converged.
    pub peer: Option<SocketAddr>,
    /// Well-formed punch packets whose token did not match ours.
    ///
    /// A cross-veil punch fails by *timing out*, which is indistinguishable
    /// from a NAT that never opened — so without this counter the new boundary
    /// would be invisible in operation. A non-zero value on a failed attempt
    /// means somebody punched at us with a token we could not recognise.
    pub foreign_tokens: u32,
}

/// Conventional port used by Core nodes that automatically offer the bounded
/// reflector service. This is a protocol default, not a central endpoint: any
/// operator can serve it and peers announce availability during their
/// authenticated Veil handshake.
pub const DEFAULT_UDP_REFLECTOR_PORT: u16 = 39_999;

/// Authenticated ATTACH transport advertisement understood by node-runtime.
/// The host is deliberately a wildcard: the receiver combines the announced
/// port with the IP address of the already-authenticated transport peer, so an
/// announcement cannot turn clients into UDP scanners for a third-party host.
pub const UDP_REFLECTOR_ADVERTISEMENT_PREFIX: &str = "veil-udp-reflector://";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UdpReflectorAdvertisement {
    /// Reflector served by the peer sending this authenticated ATTACH. The
    /// receiver supplies the peer's transport IP.
    PeerPort(u16),
    /// Bounded, transitively shared public endpoint learned from another
    /// authenticated peer.
    Endpoint(SocketAddr),
}

pub fn udp_reflector_advertisement(port: u16) -> Option<String> {
    (port != 0).then(|| format!("{UDP_REFLECTOR_ADVERTISEMENT_PREFIX}0.0.0.0:{port}"))
}

pub fn udp_reflector_endpoint_advertisement(endpoint: SocketAddr) -> Option<String> {
    (endpoint.port() != 0 && is_public_punch_addr(endpoint))
        .then(|| format!("{UDP_REFLECTOR_ADVERTISEMENT_PREFIX}{endpoint}"))
}

pub fn parse_udp_reflector_advertisement(value: &str) -> Option<UdpReflectorAdvertisement> {
    let endpoint = value
        .strip_prefix(UDP_REFLECTOR_ADVERTISEMENT_PREFIX)?
        .parse::<SocketAddr>()
        .ok()?;
    if endpoint.port() == 0 {
        return None;
    }
    if endpoint.ip().is_unspecified() {
        return Some(UdpReflectorAdvertisement::PeerPort(endpoint.port()));
    }
    is_public_punch_addr(endpoint).then_some(UdpReflectorAdvertisement::Endpoint(endpoint))
}

// A public reflector is deliberately not an authenticated service: a client
// needs its observed mapping before it can complete the authenticated punch.
// Keep the no-amplification wire invariant and also cap aggregate replies so a
// spoofed-source flood cannot turn one deployment into an unbounded 1:1 UDP
// reflector.  The burst accommodates simultaneous client restarts while the
// sustained rate limits protocol payload egress to 32 KiB/s per process.
const REFLECTOR_REPLIES_PER_SECOND: u64 = 512;
const REFLECTOR_REPLY_BURST: u64 = 1_024;

/// Fixed-size wire packet. Request == response prevents UDP amplification.
pub const UDP_PUNCH_PACKET_LEN: usize = 64;

struct ReflectorReplyLimiter {
    tokens: u64,
    last_refill: time::Instant,
}

impl ReflectorReplyLimiter {
    fn new() -> Self {
        Self {
            tokens: REFLECTOR_REPLY_BURST,
            last_refill: time::Instant::now(),
        }
    }

    fn allow(&mut self) -> bool {
        self.allow_at(time::Instant::now())
    }

    fn allow_at(&mut self, now: time::Instant) -> bool {
        let elapsed_ns = now.duration_since(self.last_refill).as_nanos();
        let replenished =
            elapsed_ns.saturating_mul(u128::from(REFLECTOR_REPLIES_PER_SECOND)) / 1_000_000_000;
        if replenished > 0 {
            self.tokens = self
                .tokens
                .saturating_add(u64::try_from(replenished).unwrap_or(u64::MAX))
                .min(REFLECTOR_REPLY_BURST);
            // A conservative reset avoids accumulating rounding credit.
            self.last_refill = now;
        }
        if self.tokens == 0 {
            return false;
        }
        self.tokens -= 1;
        true
    }
}

/// Whether a peer-advertised server-reflexive endpoint is safe to probe over
/// the public Internet. NAT signaling is authenticated but a malicious peer or
/// coordinator still controls candidate bytes; reject every local, special,
/// documentation and non-unicast range so the puncher cannot become an SSRF-
/// like UDP probe into either IPv4 or IPv6 internal networks.
pub fn is_public_punch_addr(address: SocketAddr) -> bool {
    match address.ip() {
        IpAddr::V4(ip) => {
            let octets = ip.octets();
            !(octets[0] == 0
                || ip.is_private()
                || ip.is_loopback()
                || ip.is_link_local()
                || ip.is_broadcast()
                || ip.is_documentation()
                || ip.is_multicast()
                || (octets[0] == 100 && (64..128).contains(&octets[1]))
                || (octets[0] == 192 && octets[1] == 0 && octets[2] == 0)
                || (octets[0] == 192 && octets[1] == 88 && octets[2] == 99)
                || (octets[0] == 198 && (18..=19).contains(&octets[1]))
                || octets[0] >= 240)
        }
        IpAddr::V6(ip) => {
            let segments = ip.segments();
            let first = segments[0];
            !(ip.is_unspecified()
                || ip.is_loopback()
                || ip.is_multicast()
                || (first & 0xfe00) == 0xfc00 // fc00::/7 unique-local
                || (first & 0xffc0) == 0xfe80 // fe80::/10 link-local
                || (first & 0xffc0) == 0xfec0 // fec0::/10 old site-local
                || (first == 0x2001 && segments[1] == 0x0db8) // documentation
                || (first == 0x3fff && segments[1] < 0x1000) // 3fff::/20 docs
                || (first == 0x0100 && segments[1..4] == [0, 0, 0]) // discard-only /64
                || segments[..6] == [0, 0, 0, 0, 0, 0] // deprecated v4-compatible
                || (segments[..5] == [0, 0, 0, 0, 0] && segments[5] == 0xffff))
        }
    }
}

fn packet(kind: u8, token: [u8; 16]) -> [u8; UDP_PUNCH_PACKET_LEN] {
    let mut out = [0u8; UDP_PUNCH_PACKET_LEN];
    out[..8].copy_from_slice(MAGIC);
    out[8] = kind;
    out[10..26].copy_from_slice(&token);
    out
}

/// A well-formed punch packet, whatever token it carries. Used to tell a
/// stranger's punch apart from stray traffic when counting foreign tokens.
fn is_punch_shaped(buf: &[u8]) -> bool {
    buf.len() == UDP_PUNCH_PACKET_LEN && &buf[..8] == MAGIC && buf[8] == KIND_PUNCH
}

fn valid_packet(buf: &[u8], kind: u8, token: &[u8; 16]) -> bool {
    buf.len() == UDP_PUNCH_PACKET_LEN
        && &buf[..8] == MAGIC
        && buf[8] == kind
        && &buf[10..26] == token
}

fn discovery_reply(token: [u8; 16], observed: SocketAddr) -> [u8; UDP_PUNCH_PACKET_LEN] {
    let mut out = packet(KIND_DISCOVER_REPLY, token);
    match observed.ip() {
        IpAddr::V4(ip) => {
            out[9] = 4;
            out[26..30].copy_from_slice(&ip.octets());
        }
        IpAddr::V6(ip) => {
            out[9] = 6;
            out[26..42].copy_from_slice(&ip.octets());
        }
    }
    out[42..44].copy_from_slice(&observed.port().to_be_bytes());
    out
}

fn parse_discovery_reply(buf: &[u8], token: &[u8; 16]) -> Option<SocketAddr> {
    if !valid_packet(buf, KIND_DISCOVER_REPLY, token) {
        return None;
    }
    let port = u16::from_be_bytes([buf[42], buf[43]]);
    if port == 0 {
        return None;
    }
    let ip = match buf[9] {
        4 => IpAddr::V4(Ipv4Addr::from(<[u8; 4]>::try_from(&buf[26..30]).ok()?)),
        6 => IpAddr::V6(Ipv6Addr::from(<[u8; 16]>::try_from(&buf[26..42]).ok()?)),
        _ => return None,
    };
    Some(SocketAddr::new(ip, port))
}

/// Serve fixed-size mapping-discovery requests until `shutdown` fires.
///
/// Malformed packets and punch packets are ignored. The response is exactly
/// the request size and contains only the source address the kernel observed.
pub async fn serve_udp_reflector<F>(socket: UdpSocket, shutdown: F) -> io::Result<()>
where
    F: Future,
{
    tokio::pin!(shutdown);
    let mut buf = [0u8; UDP_PUNCH_PACKET_LEN];
    let mut reply_limiter = ReflectorReplyLimiter::new();
    loop {
        tokio::select! {
            _ = &mut shutdown => return Ok(()),
            received = socket.recv_from(&mut buf) => {
                let (len, source) = received?;
                if len != UDP_PUNCH_PACKET_LEN
                    || &buf[..8] != MAGIC
                    || buf[8] != KIND_DISCOVER
                {
                    continue;
                }
                if !reply_limiter.allow() {
                    continue;
                }
                let token = <[u8; 16]>::try_from(&buf[10..26])
                    .expect("fixed packet token slice");
                let reply = discovery_reply(token, source);
                let _ = socket.send_to(&reply, source).await?;
            }
        }
    }
}

/// Discover the NAT mapping of `socket` through a public reflector.
///
/// The caller keeps ownership of the same socket for the subsequent punch and
/// QUIC promotion; creating a second socket would discover the wrong mapping.
pub async fn discover_udp_mapping(
    socket: &UdpSocket,
    reflector: SocketAddr,
    token: [u8; 16],
    timeout: Duration,
) -> io::Result<Option<SocketAddr>> {
    Ok(
        discover_udp_mapping_any(socket, &[reflector], token, timeout)
            .await?
            .map(|(mapping, _)| mapping),
    )
}

/// Discover through the first responsive reflector from a bounded redundant
/// set, using one shared deadline and the same UDP socket. Requests are the
/// same fixed 64 bytes and at most eight are sent, so an unavailable first
/// endpoint does not add a full timeout before failover.
pub async fn discover_udp_mapping_any(
    socket: &UdpSocket,
    reflectors: &[SocketAddr],
    token: [u8; 16],
    timeout: Duration,
) -> io::Result<Option<(SocketAddr, SocketAddr)>> {
    discover_udp_mapping_any_inner(socket, reflectors, token, timeout, false).await
}

/// Discover a mapping suitable for accepting unsolicited peer punch packets.
///
/// A VPN/proxy can egress UDP from the same host that runs the reflector. In
/// that topology the reflector reports its own public IP plus the proxy's
/// ephemeral source port. The response is wire-valid, but unrelated Internet
/// hosts cannot reach the client through that address; attempting it only
/// burns the direct-path deadline. Ignore such same-IP observations and keep
/// waiting for another configured reflector within the original shared
/// deadline. The generic [`discover_udp_mapping_any`] intentionally remains a
/// faithful mapping diagnostic and does not apply this reachability policy.
pub async fn discover_udp_mapping_any_for_punch(
    socket: &UdpSocket,
    reflectors: &[SocketAddr],
    token: [u8; 16],
    timeout: Duration,
) -> io::Result<Option<(SocketAddr, SocketAddr)>> {
    discover_udp_mapping_any_inner(socket, reflectors, token, timeout, true).await
}

async fn discover_udp_mapping_any_inner(
    socket: &UdpSocket,
    reflectors: &[SocketAddr],
    token: [u8; 16],
    timeout: Duration,
    reject_reflector_ip_mapping: bool,
) -> io::Result<Option<(SocketAddr, SocketAddr)>> {
    let request = packet(KIND_DISCOVER, token);
    let mut selected = Vec::with_capacity(reflectors.len().min(8));
    for reflector in reflectors.iter().copied() {
        if !selected.contains(&reflector) {
            selected.push(reflector);
        }
        if selected.len() == 8 {
            break;
        }
    }
    if selected.is_empty() {
        return Ok(None);
    }

    let mut sent = false;
    let mut last_error = None;
    for reflector in &selected {
        match socket.send_to(&request, reflector).await {
            Ok(_) => sent = true,
            Err(error) => last_error = Some(error),
        }
    }
    if !sent {
        return Err(last_error.unwrap_or_else(|| {
            io::Error::new(io::ErrorKind::InvalidInput, "no usable UDP reflectors")
        }));
    }

    let deadline = time::Instant::now() + timeout;
    let mut buf = [0u8; UDP_PUNCH_PACKET_LEN];
    let mut degenerate_responders = HashSet::new();
    loop {
        let received = match time::timeout_at(deadline, socket.recv_from(&mut buf)).await {
            // A receive that FAILS is not a reflector that could not be
            // reached: the sends above already succeeded, or this loop would
            // never have been entered. Windows makes the difference visible —
            // a datagram to a port nothing answers comes back as
            // `WSAECONNRESET` on the NEXT receive, per-datagram and
            // non-fatal, where POSIX simply waits. Propagating it made the
            // caller report `NoReflector` for a reflector that was configured,
            // parsed and sent to, sending an operator after missing config
            // instead of an unreachable host.
            //
            // Keep waiting instead: another selected reflector may still
            // answer, and the deadline above is what ends this either way.
            Ok(Err(_)) => continue,
            Ok(Ok(result)) => result,
            Err(_) => return Ok(None),
        };
        let (len, source) = received;
        if !selected.contains(&source) {
            continue;
        }
        if let Some(observed) = parse_discovery_reply(&buf[..len], &token) {
            if reject_reflector_ip_mapping && observed.ip() == source.ip() {
                degenerate_responders.insert(source);
                if degenerate_responders.len() == selected.len() {
                    return Ok(None);
                }
                continue;
            }
            return Ok(Some((observed, source)));
        }
    }
}

/// Simultaneously send and receive authenticated punch packets on `socket`.
///
/// Candidates are bounded by the protocol budget, deduplicated, and retried
/// every 50 ms until the deadline. On a valid inbound token, one final packet
/// is echoed to the observed source so the other side also converges, then the
/// peer-reflexive address is returned for QUIC promotion.
pub async fn punch_udp(
    socket: &UdpSocket,
    candidates: &[SocketAddr],
    token: [u8; 16],
    network_tag: &[u8; 32],
    timeout: Duration,
) -> io::Result<PunchOutcome> {
    let mut seen = HashSet::new();
    let candidates: Vec<SocketAddr> = candidates
        .iter()
        .copied()
        // Preserve caller-provided ICE priority order while deduplicating.
        .filter(|candidate| seen.insert(*candidate))
        .take(veil_proto::budget::MAX_HOLE_PUNCH_CANDIDATES)
        .collect();
    let mut outcome = PunchOutcome::default();
    if candidates.is_empty() {
        return Ok(outcome);
    }

    // Everything on the wire uses the bound token; the bare `token` is never
    // sent, so the binding cannot be skipped by a caller that forgets it.
    let token = bound_token(token, network_tag);
    let probe = packet(KIND_PUNCH, token);
    let deadline = time::Instant::now() + timeout;
    let mut cadence = time::interval(Duration::from_millis(50));
    cadence.set_missed_tick_behavior(time::MissedTickBehavior::Skip);
    let mut buf = [0u8; UDP_PUNCH_PACKET_LEN];
    loop {
        tokio::select! {
            _ = time::sleep_until(deadline) => return Ok(outcome),
            _ = cadence.tick() => {
                for candidate in &candidates {
                    // One unreachable candidate must not abort the whole ICE set.
                    let _ = socket.send_to(&probe, candidate).await;
                }
            }
            received = socket.recv_from(&mut buf) => {
                let (len, source) = received?;
                if !valid_packet(&buf[..len], KIND_PUNCH, &token) {
                    if is_punch_shaped(&buf[..len]) {
                        outcome.foreign_tokens = outcome.foreign_tokens.saturating_add(1);
                    }
                    continue;
                }
                let _ = socket.send_to(&probe, source).await;
                outcome.peer = Some(source);
                return Ok(outcome);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reflector_advertisement_contains_only_an_authenticated_peer_port() {
        let rendered = udp_reflector_advertisement(DEFAULT_UDP_REFLECTOR_PORT).unwrap();
        assert_eq!(
            parse_udp_reflector_advertisement(&rendered),
            Some(UdpReflectorAdvertisement::PeerPort(
                DEFAULT_UDP_REFLECTOR_PORT,
            )),
        );
        let endpoint: SocketAddr = "8.8.8.8:39999".parse().unwrap();
        let shared = udp_reflector_endpoint_advertisement(endpoint).unwrap();
        assert_eq!(
            parse_udp_reflector_advertisement(&shared),
            Some(UdpReflectorAdvertisement::Endpoint(endpoint)),
        );
        assert_eq!(
            parse_udp_reflector_advertisement("https://evil.test:39999"),
            None,
        );
        assert_eq!(
            parse_udp_reflector_advertisement("veil-udp-reflector://0.0.0.0:0"),
            None,
        );
        assert_eq!(
            parse_udp_reflector_advertisement("veil-udp-reflector://127.0.0.1:39999"),
            None,
        );
    }

    #[test]
    fn reflector_reply_limiter_caps_burst_and_refills() {
        let started = time::Instant::now();
        let mut limiter = ReflectorReplyLimiter {
            tokens: REFLECTOR_REPLY_BURST,
            last_refill: started,
        };
        for _ in 0..REFLECTOR_REPLY_BURST {
            assert!(limiter.allow_at(started));
        }
        assert!(!limiter.allow_at(started));

        let half_second = started + Duration::from_millis(500);
        for _ in 0..(REFLECTOR_REPLIES_PER_SECOND / 2) {
            assert!(limiter.allow_at(half_second));
        }
        assert!(!limiter.allow_at(half_second));
    }

    #[test]
    fn public_punch_address_filter_covers_ipv4_and_ipv6_special_ranges() {
        let allowed = [
            "1.1.1.1:443",
            "8.8.8.8:53",
            "[2606:4700:4700::1111]:53",
            "[2001:4860:4860::8888]:53",
        ];
        for value in allowed {
            let address = value.parse().unwrap();
            assert!(is_public_punch_addr(address), "expected public: {value}");
        }

        let rejected = [
            "0.0.0.1:9",
            "10.0.0.1:9",
            "100.64.0.1:9",
            "127.0.0.1:9",
            "169.254.1.1:9",
            "192.0.0.1:9",
            "192.168.1.1:9",
            "198.18.0.1:9",
            "198.51.100.1:9",
            "224.0.0.1:9",
            "240.0.0.1:9",
            "[::1]:9",
            "[::ffff:192.0.2.1]:9",
            "[100::1]:9",
            "[2001:db8::1]:9",
            "[3fff::1]:9",
            "[fc00::1]:9",
            "[fd12:3456::1]:9",
            "[fe80::1]:9",
            "[fec0::1]:9",
            "[ff02::1]:9",
        ];
        for value in rejected {
            let address = value.parse().unwrap();
            assert!(!is_public_punch_addr(address), "expected special: {value}");
        }
    }
    use tokio::sync::oneshot;

    async fn reflector() -> (
        SocketAddr,
        oneshot::Sender<()>,
        tokio::task::JoinHandle<io::Result<()>>,
    ) {
        let socket = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let addr = socket.local_addr().unwrap();
        let (shutdown_tx, shutdown_rx) = oneshot::channel();
        let task = tokio::spawn(serve_udp_reflector(socket, shutdown_rx));
        (addr, shutdown_tx, task)
    }

    #[tokio::test]
    async fn reflector_reports_the_same_socket_mapping_without_amplification() {
        let (reflector, shutdown, task) = reflector().await;
        let socket = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let local = socket.local_addr().unwrap();
        let observed = discover_udp_mapping(&socket, reflector, [7u8; 16], Duration::from_secs(1))
            .await
            .unwrap();
        assert_eq!(observed, Some(local));
        let _ = shutdown.send(());
        task.await.unwrap().unwrap();
    }

    #[tokio::test]
    async fn discovery_uses_first_responsive_reflector_without_serial_timeout() {
        let silent = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let silent_addr = silent.local_addr().unwrap();
        let (live_addr, shutdown, task) = reflector().await;
        let client = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let local = client.local_addr().unwrap();
        let started = time::Instant::now();
        let (mapping, responder) = discover_udp_mapping_any(
            &client,
            &[silent_addr, live_addr, live_addr],
            [0x61; 16],
            Duration::from_secs(1),
        )
        .await
        .unwrap()
        .expect("live reflector answers");
        assert_eq!(mapping, local);
        assert_eq!(responder, live_addr);
        assert!(started.elapsed() < Duration::from_millis(500));
        let _ = shutdown.send(());
        task.await.unwrap().unwrap();
    }

    #[tokio::test]
    async fn punch_discovery_skips_vpn_exit_mapping_and_uses_next_reflector() {
        let first_socket = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let first_addr = first_socket.local_addr().unwrap();
        let (first_shutdown_tx, first_shutdown_rx) = oneshot::channel();
        let first_task = tokio::spawn(serve_udp_reflector(first_socket, first_shutdown_rx));

        // Script the second responder with a distinct observed IP. Binding a
        // second loopback alias is not portable on macOS/Windows, while this
        // wire-level reply exercises the same selection rule deterministically.
        let second_socket = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let second_addr = second_socket.local_addr().unwrap();
        let expected_mapping: SocketAddr = "203.0.113.42:45678".parse().unwrap();
        let second_task = tokio::spawn(async move {
            let mut request = [0u8; UDP_PUNCH_PACKET_LEN];
            let (len, source) = second_socket.recv_from(&mut request).await.unwrap();
            assert_eq!(len, UDP_PUNCH_PACKET_LEN);
            let token = <[u8; 16]>::try_from(&request[10..26]).unwrap();
            let reply = discovery_reply(token, expected_mapping);
            second_socket.send_to(&reply, source).await.unwrap();
        });

        let client = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let local = client.local_addr().unwrap();
        let (mapping, responder) = discover_udp_mapping_any_for_punch(
            &client,
            &[first_addr, second_addr],
            [0x62; 16],
            Duration::from_secs(1),
        )
        .await
        .unwrap()
        .expect("independent reflector supplies a usable mapping");
        assert_ne!(local.ip(), expected_mapping.ip());
        assert_eq!(mapping, expected_mapping);
        assert_eq!(responder, second_addr);

        let _ = first_shutdown_tx.send(());
        first_task.await.unwrap().unwrap();
        second_task.await.unwrap();
    }

    #[tokio::test]
    async fn punch_discovery_fails_fast_when_only_mapping_is_reflector_hairpin() {
        let (reflector, shutdown, task) = reflector().await;
        let client = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let started = time::Instant::now();
        assert_eq!(
            discover_udp_mapping_any_for_punch(
                &client,
                &[reflector],
                [0x63; 16],
                Duration::from_secs(1),
            )
            .await
            .unwrap(),
            None,
        );
        assert!(started.elapsed() < Duration::from_millis(500));
        let _ = shutdown.send(());
        task.await.unwrap().unwrap();
    }

    #[tokio::test]
    async fn discovery_rejects_a_wrong_token() {
        let reflector = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let reflector_addr = reflector.local_addr().unwrap();
        let fake = tokio::spawn(async move {
            let mut request = [0u8; UDP_PUNCH_PACKET_LEN];
            let (_, source) = reflector.recv_from(&mut request).await.unwrap();
            let wrong = discovery_reply([9u8; 16], source);
            reflector.send_to(&wrong, source).await.unwrap();
        });
        let socket = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        assert_eq!(
            discover_udp_mapping(
                &socket,
                reflector_addr,
                [8u8; 16],
                Duration::from_millis(100),
            )
            .await
            .unwrap(),
            None,
        );
        fake.await.unwrap();
    }

    #[tokio::test]
    async fn simultaneous_punch_converges_on_both_peer_reflexive_addresses() {
        let left = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let right = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let left_addr = left.local_addr().unwrap();
        let right_addr = right.local_addr().unwrap();
        let token = [0xA5; 16];
        let tag = network_tag(Some(&[7u8; 32]));
        let left_candidates = [right_addr];
        let right_candidates = [left_addr];

        let (left_seen, right_seen) = tokio::join!(
            punch_udp(&left, &left_candidates, token, &tag, Duration::from_secs(1)),
            punch_udp(
                &right,
                &right_candidates,
                token,
                &tag,
                Duration::from_secs(1)
            ),
        );
        assert_eq!(left_seen.unwrap().peer, Some(right_addr));
        assert_eq!(right_seen.unwrap().peer, Some(left_addr));
    }

    /// The defect this binding exists for: two nodes on different veils, given
    /// the same attempt token by signalling that crossed between them, must NOT
    /// converge. Before the binding they did, and the punched path was promoted
    /// into a full session — that is how a testnet client came to hold a
    /// session with a production seed.
    ///
    /// Break-check: drop the `network_tag` argument from `bound_token` and this
    /// goes green again.
    #[tokio::test]
    async fn a_punch_does_not_converge_across_veils() {
        let left = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let right = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let left_addr = left.local_addr().unwrap();
        let right_addr = right.local_addr().unwrap();
        let token = [0xA5; 16];
        let production = network_tag(Some(&[1u8; 32]));
        let testnet = network_tag(Some(&[2u8; 32]));
        assert_ne!(
            production, testnet,
            "different PSKs must give different tags"
        );
        let to_right = [right_addr];
        let to_left = [left_addr];

        let (left_seen, right_seen) = tokio::join!(
            punch_udp(
                &left,
                &to_right,
                token,
                &production,
                Duration::from_millis(400)
            ),
            punch_udp(
                &right,
                &to_left,
                token,
                &testnet,
                Duration::from_millis(400)
            ),
        );
        let left_seen = left_seen.unwrap();
        let right_seen = right_seen.unwrap();
        assert_eq!(left_seen.peer, None, "converged across veils");
        assert_eq!(right_seen.peer, None, "converged across veils");
        // ...and the attempt is observable rather than a silent timeout.
        assert!(
            left_seen.foreign_tokens > 0 && right_seen.foreign_tokens > 0,
            "a cross-veil punch must be counted, not just time out"
        );
    }

    /// Nodes that configure no PSK are the open veil and keep working with each
    /// other exactly as before. Without this the binding would silently split
    /// every public deployment into isolated pairs.
    #[tokio::test]
    async fn nodes_without_a_psk_still_punch_each_other() {
        let left = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let right = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let left_addr = left.local_addr().unwrap();
        let right_addr = right.local_addr().unwrap();
        let public = network_tag(None);
        assert_eq!(public, PUBLIC_NETWORK_TAG);
        let to_right = [right_addr];
        let to_left = [left_addr];

        let (left_seen, right_seen) = tokio::join!(
            punch_udp(&left, &to_right, [9u8; 16], &public, Duration::from_secs(1)),
            punch_udp(&right, &to_left, [9u8; 16], &public, Duration::from_secs(1)),
        );
        assert_eq!(left_seen.unwrap().peer, Some(right_addr));
        assert_eq!(right_seen.unwrap().peer, Some(left_addr));
    }

    /// Signalling carries the bare token, so anyone who reads signalling knows
    /// it. That must not be enough to punch: the wire token is derived, never
    /// sent.
    #[tokio::test]
    async fn knowing_the_signalled_token_is_not_enough_to_punch() {
        let bound = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let observer = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let token = [0x5A; 16];
        let tag = network_tag(Some(&[3u8; 32]));
        assert_ne!(
            bound_token(token, &tag),
            token,
            "bare token went on the wire"
        );

        // The observer replays exactly what signalling gave it.
        observer
            .send_to(&packet(KIND_PUNCH, token), bound.local_addr().unwrap())
            .await
            .unwrap();
        let seen = punch_udp(
            &bound,
            &[observer.local_addr().unwrap()],
            token,
            &tag,
            Duration::from_millis(300),
        )
        .await
        .unwrap();
        assert_eq!(seen.peer, None);
        assert!(seen.foreign_tokens > 0);
    }

    #[tokio::test]
    async fn punch_rejects_wrong_token_and_obeys_deadline() {
        let left = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let right = UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let right_addr = right.local_addr().unwrap();
        let wrong = packet(KIND_PUNCH, [2u8; 16]);
        right
            .send_to(&wrong, left.local_addr().unwrap())
            .await
            .unwrap();
        let seen = punch_udp(
            &left,
            &[right_addr],
            [1u8; 16],
            &network_tag(None),
            Duration::from_millis(100),
        )
        .await
        .unwrap();
        assert_eq!(seen.peer, None);
        assert!(
            seen.foreign_tokens > 0,
            "a wrong-token punch must be counted"
        );
    }
}

#[cfg(test)]
mod silent_reflector_contract {
    use super::*;

    /// A reflector that is reachable but never answers is `Ok(None)`, not an
    /// error.
    ///
    /// The caller in `veil-node-runtime` maps ANY error from this function to
    /// "no reflector" — its comment says an error here means none was even
    /// sendable. That is the contract this pins, and it is platform-visible:
    /// Windows reports a datagram nobody answers through the NEXT receive
    /// (`WSAECONNRESET`) where POSIX simply waits.
    #[tokio::test]
    async fn a_silent_reflector_is_no_mapping_not_an_error() {
        let silent = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
        let silent_addr = silent.local_addr().unwrap();
        let socket = tokio::net::UdpSocket::bind("0.0.0.0:0").await.unwrap();

        let outcome = discover_udp_mapping_any_for_punch(
            &socket,
            &[silent_addr],
            [0x5au8; 16],
            Duration::from_millis(300),
        )
        .await;

        match outcome {
            Ok(None) => {}
            Ok(Some(mapping)) => panic!("a silent reflector answered: {mapping:?}"),
            Err(error) => panic!(
                "a reachable but silent reflector must not read as unsendable: \
                 {error:?} (kind={:?})",
                error.kind()
            ),
        }
    }
}
