#!/usr/bin/env python3
"""Derive the FFI ABI contract from the generated C header.

`include/veil_ffi.h` is generated from `crates/veilclient-ffi/src/lib.rs` by
cbindgen and gated in CI, so it is the one artefact that provably describes the
C ABI this build exposes. Everything downstream that has to agree with that ABI
is derived from it HERE, rather than restated by hand:

  * `crates/veilclient-ffi/src/abi_contract.rs`
        the SHA-256 of the header, compiled into the library and handed out by
        `veil_abi_contract_hash()`.
  * `flutter/veil_flutter/lib/src/abi_contract.dart`
        the same hash, for the Dart side to compare against BEFORE it looks up
        any other symbol, plus every numeric constant the header defines.

Why a content hash and not a version counter: a counter is only as good as the
person who remembers to bump it, and the failure it is supposed to prevent
(commit `78d57520` inserted a parameter in the MIDDLE of a callback signature
without changing the symbol name) is exactly the kind a distracted author does
not notice. A hash of the generated header cannot be forgotten -- any change to
any exported signature, struct layout, or constant moves it, and the CI gate
that already diffs the header now diffs these two files with it.

The hash deliberately covers the WHOLE header, including doc comments. A
comment-only change forcing a rebuild of both sides is a small price for never
having to argue about which parts of the header are semantically load-bearing.

`VEIL_ABI_CONTRACT_HASH` is excluded from cbindgen's output (see
`cbindgen.toml`) so that the header does not contain its own hash -- otherwise
regenerating would never reach a fixed point.

Run via ./scripts/regen-ffi-header.sh; not meant to be invoked directly.
"""

import hashlib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
HEADER = REPO / "crates" / "veilclient-ffi" / "include" / "veil_ffi.h"
RUST_OUT = REPO / "crates" / "veilclient-ffi" / "src" / "abi_contract.rs"
DART_OUT = REPO / "flutter" / "veil_flutter" / "lib" / "src" / "abi_contract.dart"

# The one define that must never round-trip into the header (it IS the hash of
# the header) plus the include guard, which carries no value.
SKIP = {"VEIL_FFI_H", "VEIL_ABI_CONTRACT_HASH"}

DEFINE_RE = re.compile(r"^#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.+?)\s*$")
# A C integer expression built only from decimal literals, the four arithmetic
# operators and parentheses. Anything else (a string, a cast, a macro call) is
# not a constant this generator will claim to understand.
INT_EXPR_RE = re.compile(r"^[0-9()+\-*/ ]+$")


def dart_name(c_name: str) -> str:
    """`VEIL_MAX_DATA_LEN` -> `veilMaxDataLen`; `MEDIA_MAGIC` -> `veilMediaMagic`."""
    body = c_name[len("VEIL_"):] if c_name.startswith("VEIL_") else c_name
    parts = [p for p in body.split("_") if p]
    return "veil" + "".join(p.capitalize() for p in parts)


def parse_defines(text: str):
    """Every `#define NAME <integer expression>` in `text`, in file order."""
    out = []
    seen = set()
    for line in text.splitlines():
        m = DEFINE_RE.match(line)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        if name in SKIP or not INT_EXPR_RE.match(expr):
            continue
        # Safe by construction: INT_EXPR_RE admits digits, whitespace, the four
        # arithmetic operators and parentheses, and nothing else -- there is no
        # name to resolve and no call to make.
        value = int(eval(expr))  # noqa: S307
        if name in seen:
            raise SystemExit(f"duplicate #define {name} in {HEADER}")
        seen.add(name)
        out.append((name, value))
    return out


BANNER = (
    "// @generated by scripts/gen-ffi-abi-contract.py from\n"
    "// crates/veilclient-ffi/include/veil_ffi.h -- DO NOT EDIT BY HAND.\n"
    "//\n"
    "// Regenerate with ./scripts/regen-ffi-header.sh; CI runs the same script\n"
    "// and diffs the result, so an edit here is reverted by the next run.\n"
)


def render_rust(digest: str) -> str:
    return (
        BANNER
        + """//
// The hash of the generated C header, compiled into the library and handed to
// foreign callers by `veil_abi_contract_hash()`. A caller that carries a
// different one was built against a different ABI: same symbol names, possibly
// different signatures, and calling through it is memory corruption rather
// than a missing-symbol error.

/// SHA-256 of `include/veil_ffi.h`, lowercase hex, NUL-terminated.
///
/// Excluded from cbindgen's output (see `cbindgen.toml`) -- a header that
/// contained its own hash could never be regenerated to a fixed point.
pub const VEIL_ABI_CONTRACT_HASH: &core::ffi::CStr = c"%s";
""" % digest
    )


def render_dart(digest: str, defines) -> str:
    lines = [
        BANNER,
        "//",
        "// The Dart half of the FFI ABI contract: the hash `native.dart` checks",
        "// before it looks up any other symbol, and every numeric constant the",
        "// header defines. Constants are DERIVED here rather than restated in",
        "// `bindings.dart`, because a restated number drifts -- the Dart payload",
        "// ceiling sat 256 bytes above the native one for as long as it did",
        "// precisely because a comment claimed the two mirrored (report7 V-07).",
        "",
        "/// SHA-256 of `crates/veilclient-ffi/include/veil_ffi.h`, lowercase hex.",
        "///",
        "/// Compare against `veil_abi_contract_hash()` from the loaded library",
        "/// BEFORE using it. See `native.dart`.",
        "const String veilAbiContractHash =",
        "    '%s';" % digest,
        "",
        "// -- Constants lifted from the generated header --------------------------",
        "",
    ]
    for name, value in defines:
        lines.append("/// `%s`" % name)
        lines.append("const int %s = %d;" % (dart_name(name), value))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not HEADER.is_file():
        raise SystemExit(f"missing generated header: {HEADER}")
    raw = HEADER.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    defines = parse_defines(raw.decode("utf-8"))

    names = [dart_name(n) for n, _ in defines]
    if len(set(names)) != len(names):
        raise SystemExit("two header defines collapse onto one Dart name")

    RUST_OUT.write_text(render_rust(digest), encoding="utf-8")
    DART_OUT.write_text(render_dart(digest, defines), encoding="utf-8")
    print(f"OK: abi contract {digest[:16]}... ({len(defines)} constants)")
    print(f"    {RUST_OUT.relative_to(REPO)}")
    print(f"    {DART_OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
