// @generated by scripts/gen-ffi-abi-contract.py from
// crates/veilclient-ffi/include/veil_ffi.h -- DO NOT EDIT BY HAND.
//
// Regenerate with ./scripts/regen-ffi-header.sh; CI runs the same script
// and diffs the result, so an edit here is reverted by the next run.

//
// The Dart half of the FFI ABI contract: the hash `native.dart` checks
// before it looks up any other symbol, and every numeric constant the
// header defines. Constants are DERIVED here rather than restated in
// `bindings.dart`, because a restated number drifts -- the Dart payload
// ceiling sat 256 bytes above the native one for as long as it did
// precisely because a comment claimed the two mirrored (report7 V-07).

/// SHA-256 of `crates/veilclient-ffi/include/veil_ffi.h`, lowercase hex.
///
/// Compare against `veil_abi_contract_hash()` from the loaded library
/// BEFORE using it. See `native.dart`.
const String veilAbiContractHash =
    '2ff51b5d1a4bf03c2b8f5ba09e7db56afa554c24bba2bbe749fa85029601e0d8';

// -- Constants lifted from the generated header --------------------------

/// `VEIL_OK`
const int veilOk = 0;
/// `VEIL_ERR`
const int veilErr = -1;
/// `VEIL_ERR_INVALID_ARG`
const int veilErrInvalidArg = -2;
/// `VEIL_ERR_CLOSED`
const int veilErrClosed = -3;
/// `VEIL_ERR_REENTRANT`
const int veilErrReentrant = -4;
/// `VEIL_MAX_DATA_LEN`
const int veilMaxDataLen = 16776960;
/// `VEIL_MAILBOX_MAX_FETCH_BYTES`
const int veilMailboxMaxFetchBytes = 8388608;
/// `VEIL_MAILBOX_MAX_FETCH_COUNT`
const int veilMailboxMaxFetchCount = 1024;
/// `VEIL_MAILBOX_MAX_BLOB_BYTES`
const int veilMailboxMaxBlobBytes = 1048576;
/// `VEIL_ABI_CONTRACT_HASH_LEN`
const int veilAbiContractHashLen = 64;
/// `VEIL_PROVENANCE_CLAIMED`
const int veilProvenanceClaimed = 0;
/// `VEIL_PROVENANCE_LOCAL_IPC`
const int veilProvenanceLocalIpc = 1;
/// `VEIL_PROVENANCE_SESSION_PEER`
const int veilProvenanceSessionPeer = 2;
/// `VEIL_PROVENANCE_SIGNED`
const int veilProvenanceSigned = 3;
/// `VEIL_BG_FOREGROUND`
const int veilBgForeground = 0;
/// `VEIL_BG_ACTIVE`
const int veilBgActive = 1;
/// `VEIL_BG_LOWPOWER`
const int veilBgLowpower = 2;
/// `VEIL_NET_OFFLINE`
const int veilNetOffline = 0;
/// `VEIL_NET_WIFI`
const int veilNetWifi = 1;
/// `VEIL_NET_CELLULAR`
const int veilNetCellular = 2;
/// `VEIL_NET_ETHERNET`
const int veilNetEthernet = 3;
/// `VEIL_NET_UNKNOWN`
const int veilNetUnknown = 255;
/// `VEIL_PUSH_OK`
const int veilPushOk = 0;
/// `VEIL_PUSH_NO_RENDEZVOUS`
const int veilPushNoRendezvous = 1;
/// `VEIL_PUSH_TOO_LARGE`
const int veilPushTooLarge = 2;
/// `VEIL_WAKE_VERDICT_VALID`
const int veilWakeVerdictValid = 0;
/// `VEIL_WAKE_VERDICT_TAMPERED`
const int veilWakeVerdictTampered = 1;
/// `VEIL_WAKE_VERDICT_EXPIRED`
const int veilWakeVerdictExpired = 2;
/// `VEIL_WAKE_VERDICT_MALFORMED`
const int veilWakeVerdictMalformed = 3;
/// `VEIL_WAKE_HMAC_KEY_LEN`
const int veilWakeHmacKeyLen = 32;
/// `VEIL_WAKE_PAYLOAD_LEN`
const int veilWakePayloadLen = 72;
/// `VEIL_RELAY_X25519_UNAVAILABLE`
const int veilRelayX25519Unavailable = -10;
/// `VEIL_MAILBOX_PUT_STORED`
const int veilMailboxPutStored = 0;
/// `VEIL_MAILBOX_PUT_DUPLICATE`
const int veilMailboxPutDuplicate = 1;
/// `VEIL_MAILBOX_PUT_QUOTA_PER_RECEIVER`
const int veilMailboxPutQuotaPerReceiver = 2;
/// `VEIL_MAILBOX_PUT_QUOTA_GLOBAL`
const int veilMailboxPutQuotaGlobal = 3;
/// `VEIL_MAILBOX_PUT_RATE_LIMITED`
const int veilMailboxPutRateLimited = 4;
/// `VEIL_MAILBOX_PUT_NOT_RELAY`
const int veilMailboxPutNotRelay = 5;
/// `VEIL_MAILBOX_PUT_CAPABILITY_REQUIRED`
const int veilMailboxPutCapabilityRequired = 6;
/// `VEIL_MAILBOX_PUT_CAPABILITY_INVALID`
const int veilMailboxPutCapabilityInvalid = 7;
/// `VEIL_MAILBOX_PUT_QUOTA_PER_SENDER`
const int veilMailboxPutQuotaPerSender = 8;
/// `VEIL_JOIN_OK`
const int veilJoinOk = 0;
/// `VEIL_JOIN_INVALID_URI`
const int veilJoinInvalidUri = 1;
/// `VEIL_JOIN_PASSWORD_REQUIRED`
const int veilJoinPasswordRequired = 2;
/// `VEIL_JOIN_PASSWORD_WRONG`
const int veilJoinPasswordWrong = 3;
/// `VEIL_JOIN_SIGNATURE_INVALID`
const int veilJoinSignatureInvalid = 4;
/// `VEIL_JOIN_INTERNAL_ERROR`
const int veilJoinInternalError = 5;
/// `VEIL_JOIN_ALREADY_REGISTERED`
const int veilJoinAlreadyRegistered = 6;
/// `VEIL_HOLE_PUNCH_CONNECTED`
const int veilHolePunchConnected = 0;
/// `VEIL_HOLE_PUNCH_NO_REFLECTOR`
const int veilHolePunchNoReflector = 1;
/// `VEIL_HOLE_PUNCH_SIGNALING_TIMEOUT`
const int veilHolePunchSignalingTimeout = 2;
/// `VEIL_HOLE_PUNCH_MAPPING_UNUSABLE`
const int veilHolePunchMappingUnusable = 3;
/// `VEIL_HOLE_PUNCH_PUNCH_TIMEOUT`
const int veilHolePunchPunchTimeout = 4;
/// `VEIL_HOLE_PUNCH_QUIC_FAILED`
const int veilHolePunchQuicFailed = 5;
/// `VEIL_HOLE_PUNCH_REFUSED_ANONYMOUS`
const int veilHolePunchRefusedAnonymous = 6;
/// `VEIL_HOLE_PUNCH_UNKNOWN_PEER`
const int veilHolePunchUnknownPeer = 7;
/// `VEIL_HOLE_PUNCH_UNSUPPORTED`
const int veilHolePunchUnsupported = 8;
/// `VEIL_CREATE_INVITE_OK`
const int veilCreateInviteOk = 0;
/// `VEIL_CREATE_INVITE_NOT_CONFIGURED`
const int veilCreateInviteNotConfigured = 1;
/// `VEIL_CREATE_INVITE_BAD_PASSWORD`
const int veilCreateInviteBadPassword = 2;
/// `VEIL_CREATE_INVITE_INTERNAL_ERROR`
const int veilCreateInviteInternalError = 3;
/// `VEIL_PEER_STATE_CONNECTING`
const int veilPeerStateConnecting = 0;
/// `VEIL_PEER_STATE_ACTIVE`
const int veilPeerStateActive = 1;
/// `VEIL_PEER_STATE_CLOSED`
const int veilPeerStateClosed = 2;
/// `VEIL_PEER_STATE_UNKNOWN`
const int veilPeerStateUnknown = 255;
/// `VEIL_PEER_DIR_INBOUND`
const int veilPeerDirInbound = 0;
/// `VEIL_PEER_DIR_OUTBOUND`
const int veilPeerDirOutbound = 1;
/// `VEIL_PUSH_ENVELOPE_OVERHEAD`
const int veilPushEnvelopeOverhead = 60;
/// `VEIL_MAX_PUSH_TOKEN_LEN`
const int veilMaxPushTokenLen = 384;
/// `VEIL_MAX_PUSH_ENVELOPE_LEN`
const int veilMaxPushEnvelopeLen = 512;
/// `VEIL_EVENT_SESSIONS_CHANGED`
const int veilEventSessionsChanged = 0;
/// `VEIL_EVENT_MOBILE_TIER_CHANGED`
const int veilEventMobileTierChanged = 1;
/// `VEIL_EVENT_IDENTITY_ROTATED`
const int veilEventIdentityRotated = 2;
/// `VEIL_EVENT_MAILBOX_DRAINED`
const int veilEventMailboxDrained = 3;
/// `VEIL_EVENT_MAILBOX_WAKE`
const int veilEventMailboxWake = 5;
/// `VEIL_DEFAULT_RESTORE_VALIDITY_SECS`
const int veilDefaultRestoreValiditySecs = 2592000;
/// `VEIL_PAIR_SOURCE_OK`
const int veilPairSourceOk = 0;
/// `VEIL_PAIR_SOURCE_NOT_CONFIGURED`
const int veilPairSourceNotConfigured = 1;
/// `VEIL_PAIR_SOURCE_ALREADY_IN_PROGRESS`
const int veilPairSourceAlreadyInProgress = 2;
/// `VEIL_PAIR_SOURCE_INTERNAL_ERROR`
const int veilPairSourceInternalError = 3;
/// `VEIL_PAIR_SOURCE_WRONG_STATE`
const int veilPairSourceWrongState = 4;
/// `VEIL_PAIR_SOURCE_BAD_HELLO`
const int veilPairSourceBadHello = 5;
/// `VEIL_PAIR_SOURCE_USER_ABORTED`
const int veilPairSourceUserAborted = 6;
/// `VEIL_PAIR_SOURCE_BAD_CONFIRM`
const int veilPairSourceBadConfirm = 7;
/// `VEIL_PAIR_TARGET_OK`
const int veilPairTargetOk = 0;
/// `VEIL_PAIR_TARGET_BAD_URI`
const int veilPairTargetBadUri = 1;
/// `VEIL_PAIR_TARGET_EXPIRED`
const int veilPairTargetExpired = 2;
/// `VEIL_PAIR_TARGET_ALREADY_IN_PROGRESS`
const int veilPairTargetAlreadyInProgress = 3;
/// `VEIL_PAIR_TARGET_BAD_CERT`
const int veilPairTargetBadCert = 4;
/// `VEIL_PAIR_TARGET_WRONG_STATE`
const int veilPairTargetWrongState = 5;
/// `VEIL_PAIR_TARGET_INTERNAL_ERROR`
const int veilPairTargetInternalError = 6;
/// `VEIL_MAX_PAIR_CEREMONY_BYTES`
const int veilMaxPairCeremonyBytes = 65536;
/// `VEIL_PAIR_OOB_CODE_LEN`
const int veilPairOobCodeLen = 6;
/// `VEIL_RATCHET_KEY_LEN`
const int veilRatchetKeyLen = 64;
/// `VEIL_RATCHET_MAX_STATE_LEN`
const int veilRatchetMaxStateLen = 262144;
/// `VEIL_ERR_RATCHET_NO_CONVERSATION`
const int veilErrRatchetNoConversation = -20;
/// `VEIL_ERR_RATCHET_BUFFER_TOO_SMALL`
const int veilErrRatchetBufferTooSmall = -21;
/// `VEIL_ERR_RATCHET_STORE_FULL`
const int veilErrRatchetStoreFull = -22;
/// `VEIL_RATCHET_MAX_CONVERSATIONS`
const int veilRatchetMaxConversations = 1024;
/// `VEIL_RATCHET_MAX_ACK_KEYS`
const int veilRatchetMaxAckKeys = 4096;
/// `STREAM_ENDPOINT_ID`
const int veilStreamEndpointId = 12;
/// `MEDIA_MAGIC`
const int veilMediaMagic = 77;
/// `MEDIA_BATCH_MAGIC`
const int veilMediaBatchMagic = 66;
/// `NICKNAME_FREE`
const int veilNicknameFree = 1;
/// `VEIL_TUNNEL_STOPPED`
const int veilTunnelStopped = 0;
/// `VEIL_TUNNEL_STARTING`
const int veilTunnelStarting = 1;
/// `VEIL_TUNNEL_RUNNING`
const int veilTunnelRunning = 2;
/// `VEIL_TUNNEL_ERROR`
const int veilTunnelError = 3;
